#!/usr/bin/env python3

# Purpose of this script is to change AMI permission upon request
import argparse
import re
from dateutil.parser import parse
import datetime
import json
import time
import boto3.ec2

parser = argparse.ArgumentParser()
parser.add_argument('--scylla_ami_id', required=True,
                    type=str, help='Scylla AMI ID')
parser.add_argument('--region', default='us-east-1',
                    type=str, help="AWS region to change permission EC2 AMIs from")
parser.add_argument('--aws_accounts', required=True, nargs='+',
                    type=str, help="List of AWS accounts that can access AMI snapshots")
parser.add_argument('--scylla_snapshot_id', required=True,
                    type=str, help="Scylla AMI snapshot-id")

args = parser.parse_args()

ec2 = boto3.client('ec2', region_name=args.region)

ec2.modify_image_attribute(ImageId=args.scylla_ami_id, OperationType='add', LaunchPermission={'Add': [{'Group': 'all'}]})

for account in args.aws_accounts:
    ec2.modify_snapshot_attribute(SnapshotId=args.scylla_snapshot_id, OperationType='add', CreateVolumePermission={'Add': [{'UserId': account}]})